# Plots fractional Brownian motion paths generated by fbm.cpp.
# Reads fbm_paths.csv and displays all simulated paths on one chart.
# Date: 11/09/2026

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("fbm_paths.csv")

plt.figure(figsize=(10, 6))

for col in data.columns[1:]:
    plt.plot(data["t"], data[col], label=col)

plt.title("Simulated Fractional Brownian Motion Paths")
plt.xlabel("t")
plt.ylabel("Value")
plt.legend()
plt.savefig("fbm_paths.png", dpi=300, bbox_inches="tight")
plt.show()
