# Plots the Brownian motion paths generated by brownian_motion.cpp
# Reads brownian_paths.csv and displays all simulated paths on one chart.
# Date: 03/09/2026

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("brownian_paths.csv")

plt.figure(figsize=(10, 6))

for col in data.columns[1:]:  # skip the 't' column, plot every path column
    plt.plot(data["t"], data[col], label=col)

plt.title("Simulated Brownian Motion Paths")
plt.xlabel("t")
plt.ylabel("Value")
plt.legend()
plt.show()
